require ("prototypes.item")
require ("prototypes.entity")
require ("prototypes.recipe")
require ("prototypes.technology")
require ("prototypes.sprites")
require ("prototypes.styles")
require ("prototypes.custom-input")