name: Run unit tests
on:
  push:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Run Busted
        uses: lunarmodules/busted
        with:
          args: -o TAP
