name: Run unit tests
on:
  push:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Install lua
        run: sudo apt install lua5.2
      - name: Install luarock
        run: sudo apt install luarocks
